vars:
- params.yaml

stages:
  join:
    wdir: .
    desc: Concatenate any number of datasets so they can be used as one for training
    cmd: >
      lyscripts data join
      --inputs 2021-usz-oropharynx/data.csv 2021-clb-oropharynx/data.csv 2023-isb-multisite/data.csv 2023-clb-multisite/data.csv 2024-hvh-oropharynx/data.csv 2025-umcg-hypopharynx-larynx/data.csv 2025-usz-hypopharynx-larynx/data.csv
      --output data/joined_${model.num_components}.csv
    deps:
    - 2021-usz-oropharynx/data.csv
    - 2021-clb-oropharynx/data.csv
    - 2023-isb-multisite/data.csv
    - 2023-clb-multisite/data.csv
    - 2024-hvh-oropharynx/data.csv
    - 2025-umcg-hypopharynx-larynx/data.csv
    - 2025-usz-hypopharynx-larynx/data.csv
    outs:
    - data/joined_${model.num_components}.csv
    params:
    - model.num_components

  enhance:
    wdir: .
    desc:
      This stage fixes the super- and sub-level reporting for the LNLs and also creates
      new 'modalities' from combining existing ones, e.g. using the logical AND or
      estimating the most likely involvement based on the observations only.
    cmd: >
      lyscripts data enhance data/joined_${model.num_components}.csv data/enhanced_${model.num_components}.csv ${data_cleaning_modalities}
    deps:
    - data/joined_${model.num_components}.csv
    params:
    - modalities
    - model.num_components
    outs:
    - data/enhanced_${model.num_components}.csv

  filter:
    wdir: .
    desc:
      Select patients with oral cavity, oropharynx, hypopharynx and larynx subsites.
      Further reduce the ICD codes.
    cmd: >
      python scripts/filter_and_reduce.py
      --locations ${data.locations}
      --input data/enhanced_${model.num_components}.csv
      --output data/filtered_${model.num_components}.csv
    deps:
      - scripts/filter_and_reduce.py
      - data/enhanced_${model.num_components}.csv
    params:
    - data
    - model.num_components
    outs:
      - data/filtered_${model.num_components}.csv

  fitting:
    wdir: .
    desc:
      Fit mixture model 
    cmd: >
      lyscripts mixture_fit
    deps:
    - ${general.data}
    outs:
    - ${fitting.folder_path}
    params:
    - graph
    - model
    - em
    - modalities
    - general

  plot-mixture-matrix:
    wdir: .
    desc: Plots the mixture component matrix.
    cmd: >
      lyscripts plot mixture_plot
      --input ${fitting.folder_path}/mixture_coef.csv
      --output ${general.plots_dir}/mixture_matrix_${model.num_components}_comp
    deps:
    - ${fitting.folder_path}
    plots:
    - ${general.plots_dir}/mixture_matrix_${model.num_components}_comp.png
    - ${general.plots_dir}/mixture_matrix_${model.num_components}_comp.svg
    params:
    - general
    - fitting
    - model.num_components

  # plot-simplex:
  #   wdir: .
  #   desc: Plots the simplex representation of the mixture coefficients
  #   cmd: >
  #     lyscripts plot simplex_plot
  #     --input ${fitting.folder_path}/mixture_coef.csv
  #     --output ${general.plots_dir}/simplex_4_comp
  #   deps:
  #     - ${fitting.folder_path}
  #   plots:
  #   - ${general.plots_dir}/simplex_4_comp.png
  #   - ${general.plots_dir}/simplex_4_comp.svg
  #   params:
  #   - general

  # bootstrap:
  #   wdir: .
  #   cmd: >
  #     lyscripts data bootstrap 
  #     --output ${sampling.folder_path}
  #     --input ${general.data}
  #   deps:
  #   - ${general.data}
  #   outs:
  #   - ${sampling.folder_path}
  #   params:
  #   - sampling

  # refitting:
  #   wdir: .
  #   desc:
  #     Re-fit mixture model on bootstrapped data
  #   cmd: >
  #     lyscripts mixture_fit -m True -sp ${sampling.starting_points} -i ${sampling.folder_path}
  #   deps:
  #   - ${sampling.folder_path}
  #   params:
  #   - sampling
  #   - graph
  #   - model
  #   - em
  #   - modalities
  #   - general
  #   - data
  #   outs:
  #   - ${sampling.output_path}

  plot-comp-uncert:
    wdir: .
    desc:
      Plot uncertainty in mixture components from bootstrapped refitting
    cmd: >
      lyscripts plot mixture_comp_uncertainty
      --optimal_params ${fitting.folder_path}/optimal_params.csv
      --input ${sampling.output_path}/optimal_params
      --output ${general.plots_dir}/mixture_comp_uncertainty_${model.num_components}_comp.png
    deps:
    - ${fitting.folder_path}/optimal_params.csv
    - ${sampling.output_path}/optimal_params
    plots:
    - ${general.plots_dir}/mixture_comp_uncertainty_${model.num_components}_comp.png
    - ${general.plots_dir}/mixture_comp_uncertainty_${model.num_components}_comp.svg
    params:
    - general
    - fitting
    - sampling
    - model.num_components